version: 0.2
phases:
  build:
    commands:
      - pip install --upgrade awscli
      - export BUCKET=codepipeline-lambda-bucket-course
      - python -m unittest discover tests
      - >-
        aws cloudformation package --template-file template.yml --s3-bucket
        $BUCKET --output-template-file template-out.yml
artifacts:
  type: zip
  files:
    - template.yml
    - template-out.yml
